### ISSUE TITLE
Any plans on creating a release?

### ISSUE THREAD

**Issue by ratulmukh** [OpenHFT/Chronicle-TimeSeries#1]

**Comment by peter-lawrey** [comment]
I think it needs some more features really.

What would you like to see in it?

**Comment by ratulmukh** [comment]
Ok. I don't have anything concrete in mind right now. I was exploring and thought this was an interesting project.

**Comment by peter-lawrey** [comment]
I would explore it from the source for now. If you want to contributor can
fork it first and issue pull requests.

**Comment by RobAustin** [comment]
closing as we replied on 3 Sep 2016

**Comment by nikkekin** [comment]
I would like to give this one a try, but lack of a release is a bit problematic.

I wouldn't like to clone it and build it just for that, but can of course do so if that is the only way...

Just looking for an efficient in-memory tick storage at the moment, if you have some other suggestions I would be open to those too if this project is dead.
